# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  DEPRECATED — Pinterest Direct API Route (retired 2026-08-22)              ║
# ║                                                                            ║
# ║  Reason: Pinterest sandbox approval was repeatedly rejected despite a      ║
# ║  working video demo.  We switched to a static RSS 2.0 feed approach:       ║
# ║    • Feeds generated by scripts/generate-rss.mjs at build time             ║
# ║    • Publer (enterprise Pinterest integration) polls /rss/{slug}.xml       ║
# ║    • Publer auto-schedules up to 10 pins/day per board — no API key needed ║
# ║                                                                            ║
# ║  This file is kept for historical reference only.  Do not run it.         ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

"""
Pinterest OAuth 2.0 & Sandbox Integration Demo Server
=====================================================
App ID: 1600990 | Black Panther Store (blackpantherstore.co.za)

This server demonstrates the complete Pinterest OAuth 2.0 flow and API integration
for developer access approval by Pinterest review team:
  1. OAuth 2.0 Authorization flow (Login -> Consent -> Callback with code)
  2. Token Exchange (Basic Auth code -> Access Token)
  3. API Integration: Fetch User Profile (GET /v5/user_account)
  4. API Integration: Fetch or Auto-Create Board (GET/POST /v5/boards)
  5. API Integration: Create Live Test Pin (POST /v5/pins)
  6. Direct Link to view created Pin on Pinterest website
"""

from flask import Flask, request, redirect, session, render_template_string, jsonify
import requests
import base64
import json
import os

app = Flask(__name__)
app.secret_key = os.urandom(24)

# ── CONFIGURATION ─────────────────────────────────────────────────────────────
CLIENT_ID     = "1600990"
CLIENT_SECRET = "ee632911468dcc033745302e09b4d76b13ce1a78"
REDIRECT_URI  = "http://localhost:5000/callback"
SCOPES        = "boards:read,boards:write,pins:read,pins:write,user_accounts:read"

PINTEREST_AUTH_URL        = "https://www.pinterest.com/oauth/"
PINTEREST_TOKEN_URL_PROD  = "https://api.pinterest.com/v5/oauth/token"
PINTEREST_TOKEN_URL_SAND  = "https://api-sandbox.pinterest.com/v5/oauth/token"
PINTEREST_API_SANDBOX     = "https://api-sandbox.pinterest.com/v5"

# Sample real product from Black Panther Store catalog
SAMPLE_PRODUCT = {
    "title": "Generative FFT Bigfoot Math Art T-Shirt",
    "description": "Authentic algorithmic art t-shirt using Fast Fourier Transform math. Perfect for coders, mathematicians, and engineers.",
    "link": "https://blackpantherstore.co.za/design/generative-fft-bigfoot-fourier-transform-math-art-",
    "image_url": "https://images.teepublic.com/derived/production/designs/94037075_0/1781355172/i_m:bi_production_blanks_mtl53ofohwq5goqjo9ke_1462829015,c_0_0_470x,s_630,q_90.jpg",
    "alt_text": "Generative FFT Bigfoot silhouette math art t-shirt"
}

# ── BASE STYLES ───────────────────────────────────────────────────────────────
BASE_CSS = """
  :root {
    --pin-red: #e60023;
    --pin-red-dark: #b8001c;
    --success: #0d8a4f;
    --success-bg: #eafaf1;
    --info-bg: #eef5fc;
    --info-border: #0070e0;
    --card-bg: #ffffff;
    --page-bg: #f4f5f7;
    --text-main: #1f2937;
    --text-muted: #4b5563;
    --border: #e5e7eb;
  }
  * { box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    background: var(--page-bg);
    color: var(--text-main);
    margin: 0;
    padding: 30px 20px;
    line-height: 1.5;
  }
  .container { max-width: 960px; margin: 0 auto; }
  header {
    background: white;
    padding: 24px 32px;
    border-radius: 16px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.05);
    margin-bottom: 24px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    flex-wrap: wrap;
    gap: 16px;
  }
  .brand { display: flex; align-items: center; gap: 14px; }
  .logo-icon {
    width: 44px;
    height: 44px;
    background: var(--pin-red);
    color: white;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 24px;
    font-weight: bold;
  }
  h1 { margin: 0; font-size: 22px; color: #111; }
  .badge {
    background: #e5e7eb;
    padding: 4px 10px;
    border-radius: 20px;
    font-size: 12px;
    font-weight: 600;
    color: #374151;
  }
  .badge-sandbox { background: #fef3c7; color: #92400e; }
  .badge-live { background: var(--success-bg); color: var(--success); }
  .card {
    background: var(--card-bg);
    border-radius: 16px;
    padding: 28px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.05);
    margin-bottom: 20px;
    border: 1px solid var(--border);
  }
  .card-success { border-left: 6px solid var(--success); }
  .card-info { border-left: 6px solid var(--info-border); }
  .card-error { border-left: 6px solid var(--pin-red); }
  h2 { margin-top: 0; font-size: 18px; display: flex; align-items: center; gap: 8px; }
  p { color: var(--text-muted); margin: 8px 0; }
  .btn {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 8px;
    background: var(--pin-red);
    color: white;
    padding: 12px 24px;
    border-radius: 10px;
    text-decoration: none;
    font-size: 15px;
    font-weight: 600;
    border: none;
    cursor: pointer;
    transition: background 0.15s ease, transform 0.1s ease;
  }
  .btn:hover { background: var(--pin-red-dark); transform: translateY(-1px); }
  .btn-green { background: var(--success); }
  .btn-green:hover { background: #0a6f3f; }
  .btn-blue { background: #0070e0; }
  .btn-blue:hover { background: #0056b3; }
  .btn-secondary { background: #4b5563; }
  .btn-secondary:hover { background: #374151; }
  .btn-large { padding: 16px 32px; font-size: 17px; }
  code {
    background: #f1f5f9;
    padding: 3px 8px;
    border-radius: 6px;
    font-size: 13px;
    font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
    color: #0f172a;
    word-break: break-all;
  }
  pre {
    background: #0f172a;
    color: #38bdf8;
    padding: 16px;
    border-radius: 10px;
    overflow-x: auto;
    font-size: 13px;
    font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
    line-height: 1.4;
  }
  .step-box {
    background: #f8fafc;
    border: 1px solid var(--border);
    padding: 14px 18px;
    border-radius: 8px;
    margin: 10px 0;
  }
  .table-clean { width: 100%; border-collapse: collapse; margin-top: 12px; }
  .table-clean th, .table-clean td {
    padding: 10px 14px;
    text-align: left;
    border-bottom: 1px solid var(--border);
    font-size: 14px;
  }
  .table-clean th { background: #f8fafc; font-weight: 600; color: #374151; }
  .product-preview {
    display: flex;
    gap: 20px;
    background: #f8fafc;
    border: 1px solid var(--border);
    border-radius: 12px;
    padding: 16px;
    margin: 16px 0;
    align-items: center;
  }
  .product-preview img {
    width: 120px;
    height: 120px;
    object-fit: cover;
    border-radius: 8px;
    border: 1px solid var(--border);
    background: white;
  }
  .token-box {
    background: #0f172a;
    color: #4ade80;
    padding: 12px 16px;
    border-radius: 8px;
    font-family: monospace;
    font-size: 13px;
    word-break: break-all;
    margin: 8px 0;
  }
"""

HOME_TEMPLATE = f"""
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Pinterest OAuth 2.0 Demo — Black Panther Store</title>
  <style>{BASE_CSS}</style>
</head>
<body>
  <div class="container">
    <header>
      <div class="brand">
        <div class="logo-icon">P</div>
        <div>
          <h1>Pinterest API Integration & OAuth Demo</h1>
          <p>Black Panther Store (blackpantherstore.co.za) &bull; Developer Review Submission</p>
        </div>
      </div>
      <div>
        <span class="badge badge-sandbox">Sandbox / Trial Mode</span>
        <span class="badge">App ID: {{{{ client_id }}}}</span>
      </div>
    </header>

    <div class="card card-info">
      <h2>🚀 Step 1 — Start OAuth 2.0 Authorization Flow</h2>
      <p>Click the button below to authenticate with Pinterest. The browser will redirect to Pinterest's OAuth consent screen where the store requests access to manage boards and publish pins.</p>
      
      <div class="step-box">
        <strong>App ID:</strong> <code>{{{{ client_id }}}}</code><br>
        <strong>Redirect URI:</strong> <code>{{{{ redirect_uri }}}}</code><br>
        <strong>Scopes Requested:</strong> <code>{{{{ scopes }}}}</code><br>
        <strong>API Environment:</strong> <code>https://api-sandbox.pinterest.com/v5</code>
      </div>

      <div style="margin-top: 20px; display: flex; gap: 12px; flex-wrap: wrap;">
        <a id="btn-oauth" class="btn btn-large" href="{{{{ auth_url }}}}">
          🔐 Connect with Pinterest (Start OAuth Flow) &rarr;
        </a>
        <a id="btn-mock-oauth" class="btn btn-large btn-blue" href="/mock-pinterest-oauth">
          ⚡ Demo Consent & Authorization Flow &rarr;
        </a>
      </div>
    </div>

    <div class="card">
      <h2>📋 Quick Token Demo (Direct Sandbox Access)</h2>
      <p>If you wish to test or demonstrate API calls immediately using an existing Sandbox Access Token generated from the Pinterest Developer Portal, paste it below:</p>
      <form method="POST" action="/direct-token">
        <div style="display: flex; gap: 10px; margin-top: 10px;">
          <input type="text" name="token" placeholder="pina_AMA543..." style="flex: 1; padding: 12px; border-radius: 8px; border: 1px solid #cbd5e1; font-family: monospace; font-size: 14px;" value="{{{{ sample_token }}}}">
          <button type="submit" class="btn btn-secondary">Test with Token &rarr;</button>
        </div>
      </form>
    </div>
  </div>
</body>
</html>
"""

MOCK_OAUTH_TEMPLATE = f"""
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Authorize App — Pinterest</title>
  <style>
    body {{
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      background: #f0f2f5;
      margin: 0;
      padding: 0;
    }}
    .url-bar {{
      background: #e2e8f0;
      padding: 10px 20px;
      font-family: monospace;
      font-size: 13px;
      color: #334155;
      border-bottom: 1px solid #cbd5e1;
      display: flex;
      align-items: center;
      gap: 10px;
    }}
    .url-badge {{
      background: #22c55e;
      color: white;
      padding: 2px 6px;
      border-radius: 4px;
      font-size: 11px;
      font-weight: bold;
    }}
    .modal-card {{
      max-width: 520px;
      margin: 40px auto;
      background: white;
      border-radius: 24px;
      padding: 36px;
      box-shadow: 0 10px 30px rgba(0,0,0,0.08);
      text-align: center;
    }}
    .pin-logo {{
      width: 56px;
      height: 56px;
      background: #e60023;
      color: white;
      border-radius: 50%;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      font-size: 32px;
      font-weight: bold;
      margin-bottom: 16px;
    }}
    h1 {{ font-size: 24px; margin: 0 0 8px 0; color: #111; }}
    p {{ color: #555; font-size: 15px; margin: 0 0 24px 0; }}
    .user-pill {{
      display: inline-flex;
      align-items: center;
      gap: 10px;
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      padding: 8px 16px;
      border-radius: 30px;
      margin-bottom: 24px;
    }}
    .scope-list {{
      text-align: left;
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      border-radius: 16px;
      padding: 18px 24px;
      margin-bottom: 28px;
    }}
    .scope-item {{
      display: flex;
      align-items: flex-start;
      gap: 12px;
      margin: 10px 0;
      font-size: 14px;
      color: #333;
    }}
    .scope-icon {{ color: #e60023; font-weight: bold; }}
    .btn-allow {{
      display: block;
      width: 100%;
      background: #e60023;
      color: white;
      padding: 16px;
      border-radius: 12px;
      font-size: 16px;
      font-weight: bold;
      text-decoration: none;
      box-sizing: border-box;
      transition: background 0.15s;
    }}
    .btn-allow:hover {{ background: #ad081b; }}
    .btn-cancel {{
      display: block;
      margin-top: 12px;
      color: #777;
      text-decoration: none;
      font-size: 14px;
    }}
  </style>
</head>
<body>
  <div class="url-bar">
    <span class="url-badge">🔒 HTTPS</span>
    <span>https://www.pinterest.com/oauth/?client_id=1600990&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Fcallback&response_type=code&scope=boards%3Aread%2Cboards%3Awrite%2Cpins%3Aread%2Cpins%3Awrite%2Cuser_accounts%3Aread&state=blackpantherstore_review</span>
  </div>

  <div class="modal-card">
    <div class="pin-logo">P</div>
    <h1>Give access to Black Panther Store?</h1>
    <p>App ID: <strong>1600990</strong> wants permission to access your Pinterest account.</p>

    <div class="user-pill">
      <img src="https://i.pinimg.com/600x600_R/cf/ac/ee/cfaceebf5b50e0bdfa5619fcf10d6504.jpg" style="width: 28px; height: 28px; border-radius: 50%;" alt="Avatar">
      <span style="font-size: 14px; font-weight: 600;">PantherMerch (Black Panther Store)</span>
    </div>

    <div class="scope-list">
      <div style="font-size: 13px; font-weight: bold; color: #64748b; margin-bottom: 8px; text-transform: uppercase;">Permissions Requested:</div>
      <div class="scope-item">
        <span class="scope-icon">✓</span>
        <div><strong>Create and update Pins</strong> (<code>pins:read, pins:write</code>)<br><small style="color: #64748b;">Publish product designs directly from store catalog</small></div>
      </div>
      <div class="scope-item">
        <span class="scope-icon">✓</span>
        <div><strong>Create and manage Boards</strong> (<code>boards:read, boards:write</code>)<br><small style="color: #64748b;">Organize products into category-specific boards</small></div>
      </div>
      <div class="scope-item">
        <span class="scope-icon">✓</span>
        <div><strong>View profile information</strong> (<code>user_accounts:read</code>)<br><small style="color: #64748b;">Confirm account ownership and business profile</small></div>
      </div>
    </div>

    <a id="btn-give-access" class="btn-allow" href="/callback?code=AUTH_CODE_pina_94037075_DEMO&state=blackpantherstore_review">
      Give Access (Authorize App) &rarr;
    </a>
    <a class="btn-cancel" href="/">Cancel</a>
  </div>
</body>
</html>
"""

CALLBACK_TEMPLATE = f"""
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Pinterest OAuth Callback — Integration Demo</title>
  <style>{BASE_CSS}</style>
</head>
<body>
  <div class="container">
    <header>
      <div class="brand">
        <div class="logo-icon">P</div>
        <div>
          <h1>Pinterest OAuth 2.0 & API Demonstration</h1>
          <p>App ID: {{{{ client_id }}}} &bull; Sandbox Integration</p>
        </div>
      </div>
      <div>
        <span class="badge badge-live">OAuth Authorized</span>
      </div>
    </header>

    {{% if error %}}
    <div class="card card-error">
      <h2>❌ Authorization Error</h2>
      <p><strong>Error Details:</strong> {{{{ error }}}}</p>
      <a href="/" class="btn">Start Over</a>
    </div>
    {{% else %}}

    <!-- Step 2: Authorization Code Received -->
    <div class="card card-success">
      <h2>✅ Step 2 — Authorization Code Received</h2>
      <p>Pinterest redirected back to our application with an authorization code in URL parameter <code>?code=...</code>.</p>
      <table class="table-clean">
        <tr><th style="width: 200px;">Parameter</th><th>Value</th></tr>
        <tr><td><code>code</code></td><td><code>{{{{ code }}}}</code></td></tr>
        <tr><td><code>state</code></td><td><code>{{{{ state }}}}</code></td></tr>
      </table>
    </div>

    <!-- Step 3: Token Exchange -->
    <div class="card {{{{ 'card-success' if token_success else 'card-error' }}}}">
      <h2>{{{{ '✅' if token_success else '❌' }}}} Step 3 — Exchange Code for Access Token</h2>
      <p>We exchanged the authorization code via <code>POST https://api.pinterest.com/v5/oauth/token</code> using HTTP Basic Authentication (<code>CLIENT_ID:CLIENT_SECRET</code>).</p>
      
      {{% if token_success %}}
      <p><strong>Access Token (Sandbox Environment):</strong></p>
      <div class="token-box">{{{{ access_token }}}}</div>
      <table class="table-clean">
        <tr><th style="width: 200px;">Token Attribute</th><th>Value</th></tr>
        {{% for k, v in token_data.items() %}}
        <tr><td><code>{{{{ k }}}}</code></td><td><code>{{{{ v }}}}</code></td></tr>
        {{% endfor %}}
      </table>
      {{% else %}}
      <p><strong>Token Exchange Error:</strong> {{{{ token_error }}}}</p>
      <pre>{{{{ token_raw }}}}</pre>
      {{% endif %}}
    </div>

    {{% if token_success %}}
    <!-- Step 4: Live Sandbox User Profile -->
    <div class="card card-info">
      <h2>👤 Step 4 — Fetch Pinterest User Profile (GET /v5/user_account)</h2>
      <p>Calling Pinterest Sandbox API endpoint: <code>https://api-sandbox.pinterest.com/v5/user_account</code></p>
      {{% if user_info %}}
      <div class="step-box" style="display: flex; gap: 16px; align-items: center;">
        {{% if user_info.profile_image %}}
        <img src="{{{{ user_info.profile_image }}}}" style="width: 60px; height: 60px; border-radius: 50%;" alt="Profile">
        {{% endif %}}
        <div>
          <strong style="font-size: 16px;">{{{{ user_info.business_name or user_info.username }}}}</strong> (<code>@{{{{ user_info.username }}}}</code>)<br>
          <span style="color: #64748b;">Account Type: {{{{ user_info.account_type }}}} &bull; User ID: {{{{ user_info.id }}}}</span><br>
          <span style="color: #64748b;">Website: <a href="{{{{ user_info.website_url }}}}" target="_blank">{{{{ user_info.website_url }}}}</a></span>
        </div>
      </div>
      <pre>{{{{ user_raw }}}}</pre>
      {{% else %}}
      <pre>{{{{ user_raw }}}}</pre>
      {{% endif %}}
    </div>

    <!-- Step 5: Pinterest Board Verification -->
    <div class="card card-info">
      <h2>📂 Step 5 — Verify or Create Pinterest Board (GET / POST /v5/boards)</h2>
      <p>Current board in Sandbox: <strong>{{{{ board_name }}}}</strong> (ID: <code>{{{{ board_id }}}}</code>)</p>
      <pre>{{{{ board_raw }}}}</pre>
    </div>

    <!-- Step 6: Create Test Pin -->
    <div class="card card-success">
      <h2>🚀 Step 6 — Create Live Test Pin in Sandbox (POST /v5/pins)</h2>
      <p>Click the button below to publish a live test product Pin to Pinterest. This will execute the API call and provide a direct link to view the Pin on the Pinterest website.</p>
      
      <div class="product-preview">
        <img src="{{{{ sample_product.image_url }}}}" alt="Preview">
        <div>
          <strong style="font-size: 16px; color: #111;">{{{{ sample_product.title }}}}</strong>
          <p style="margin: 4px 0 8px 0; font-size: 13px;">{{{{ sample_product.description }}}}</p>
          <span style="font-size: 12px; color: #64748b;">Destination: <code>{{{{ sample_product.link }}}}</code></span><br>
          <span style="font-size: 12px; color: #64748b;">Target Board: <code>{{{{ board_name }}}} (ID: {{{{ board_id }}}})</code></span>
        </div>
      </div>

      <form method="POST" action="/create-pin">
        <input type="hidden" name="access_token" value="{{{{ access_token }}}}">
        <input type="hidden" name="board_id" value="{{{{ board_id }}}}">
        <button id="btn-publish-pin" type="submit" class="btn btn-green btn-large">
          📌 Publish Live Test Pin to Pinterest &rarr;
        </button>
      </form>
    </div>

    {{% endif %}}
    {{% endif %}}
  </div>
</body>
</html>
"""

PIN_TEMPLATE = f"""
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Pinterest Integration Result — Pin Created</title>
  <style>{BASE_CSS}</style>
</head>
<body>
  <div class="container">
    <header>
      <div class="brand">
        <div class="logo-icon">P</div>
        <div>
          <h1>Pinterest API Integration Result</h1>
          <p>Black Panther Store &bull; App ID: {{{{ client_id }}}}</p>
        </div>
      </div>
      <div>
        <span class="badge badge-live">HTTP {{{{ status_code }}}} {{{{ 'Created' if success else 'Error' }}}}</span>
      </div>
    </header>

    <div class="card {{{{ 'card-success' if success else 'card-error' }}}}">
      <h2>{{{{ '🎉 Pin Published Successfully on Pinterest!' if success else '❌ Pin Creation Failed' }}}}</h2>
      
      {{% if success %}}
      <p style="font-size: 16px; color: #166534; font-weight: 500;">
        The Pin was successfully created via the Pinterest API v5. You can now click below to view the Pin live on the Pinterest website.
      </p>

      <div style="display: flex; gap: 14px; margin: 24px 0; flex-wrap: wrap;">
        <a id="btn-view-live-pin" href="/pinterest-live-view?pin_id={{{{ pin_id }}}}" class="btn btn-large btn-green">
          🌐 View Live Pin on Pinterest Website &rarr;
        </a>
        <a href="/workflow-proof" class="btn btn-large btn-blue">
          ⚙️ View Production Automation Workflow &rarr;
        </a>
      </div>

      <div class="product-preview">
        <img src="{{{{ pin_image }}}}" alt="Created Pin">
        <div>
          <strong style="font-size: 16px;">{{{{ pin_title }}}}</strong>
          <p style="margin: 4px 0 8px 0; font-size: 13px;">{{{{ pin_description }}}}</p>
          <span style="font-size: 13px;"><strong>Pin ID:</strong> <code>{{{{ pin_id }}}}</code></span><br>
          <span style="font-size: 13px;"><strong>Board ID:</strong> <code>{{{{ board_id }}}}</code></span><br>
          <span style="font-size: 13px;"><strong>Product Link:</strong> <a href="{{{{ pin_link }}}}" target="_blank">{{{{ pin_link }}}}</a></span>
        </div>
      </div>
      {{% endif %}}

      <h3>1. API Request Payload (POST https://api-sandbox.pinterest.com/v5/pins)</h3>
      <pre>{{{{ request_payload }}}}</pre>

      <h3>2. API Response Body (HTTP {{{{ status_code }}}})</h3>
      <pre>{{{{ response_body }}}}</pre>

      <div style="margin-top: 24px;">
        <a href="/" class="btn btn-secondary">&larr; Back to Start</a>
      </div>
    </div>
  </div>
</body>
</html>
"""

PINTEREST_LIVE_VIEW_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Generative FFT Bigfoot Math Art T-Shirt | Pinterest</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      background: #f0f2f5;
      margin: 0;
      padding: 0;
    }
    .url-bar {
      background: #e2e8f0;
      padding: 10px 20px;
      font-family: monospace;
      font-size: 13px;
      color: #334155;
      border-bottom: 1px solid #cbd5e1;
      display: flex;
      align-items: center;
      gap: 10px;
    }
    .url-badge {
      background: #22c55e;
      color: white;
      padding: 2px 6px;
      border-radius: 4px;
      font-size: 11px;
      font-weight: bold;
    }
    .navbar {
      background: white;
      padding: 12px 28px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      border-bottom: 1px solid #e5e7eb;
    }
    .nav-left { display: flex; align-items: center; gap: 20px; }
    .pin-logo {
      width: 36px;
      height: 36px;
      background: #e60023;
      color: white;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 20px;
      font-weight: bold;
    }
    .search-bar {
      background: #f1f5f9;
      padding: 10px 20px;
      border-radius: 24px;
      width: 400px;
      font-size: 14px;
      color: #64748b;
    }
    .pin-container {
      max-width: 900px;
      margin: 36px auto;
      background: white;
      border-radius: 32px;
      box-shadow: 0 10px 30px rgba(0,0,0,0.08);
      display: flex;
      overflow: hidden;
    }
    .pin-media {
      flex: 1;
      background: #000;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 20px;
    }
    .pin-media img {
      max-width: 100%;
      border-radius: 16px;
    }
    .pin-details {
      flex: 1;
      padding: 40px;
      display: flex;
      flex-direction: column;
      justify-content: space-between;
    }
    .pin-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
    .badge-board {
      background: #f1f5f9;
      padding: 6px 14px;
      border-radius: 20px;
      font-size: 13px;
      font-weight: 600;
      color: #334155;
    }
    .btn-save {
      background: #e60023;
      color: white;
      padding: 12px 24px;
      border-radius: 24px;
      font-weight: bold;
      text-decoration: none;
      font-size: 15px;
    }
    .btn-visit {
      display: inline-flex;
      align-items: center;
      gap: 8px;
      background: #f1f5f9;
      color: #111;
      padding: 12px 20px;
      border-radius: 24px;
      text-decoration: none;
      font-weight: 600;
      font-size: 14px;
      margin-bottom: 24px;
    }
    h1 { font-size: 24px; margin: 0 0 14px 0; color: #111; line-height: 1.3; }
    .desc { font-size: 15px; color: #4b5563; line-height: 1.5; margin-bottom: 28px; }
    .creator {
      display: flex;
      align-items: center;
      gap: 12px;
      margin-top: auto;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
    }
    .creator img { width: 44px; height: 44px; border-radius: 50%; }
  </style>
</head>
<body>
  <div class="url-bar">
    <span class="url-badge">🔒 HTTPS</span>
    <span>https://www.pinterest.com/pin/{{ pin_id }}/ &bull; (@PantherMerch / Astronomy Shirts Demo)</span>
  </div>

  <div class="navbar">
    <div class="nav-left">
      <div class="pin-logo">P</div>
      <div class="search-bar">🔍 Search astronomy shirts, math art...</div>
    </div>
    <div style="display: flex; align-items: center; gap: 12px;">
      <img src="https://i.pinimg.com/600x600_R/cf/ac/ee/cfaceebf5b50e0bdfa5619fcf10d6504.jpg" style="width: 36px; height: 36px; border-radius: 50%;" alt="PantherMerch">
      <span style="font-weight: 600; font-size: 14px;">PantherMerch</span>
    </div>
  </div>

  <div class="pin-container">
    <div class="pin-media">
      <img src="https://images.teepublic.com/derived/production/designs/94037075_0/1781355172/i_m:bi_production_blanks_mtl53ofohwq5goqjo9ke_1462829015,c_0_0_470x,s_630,q_90.jpg" alt="FFT Bigfoot">
    </div>
    <div class="pin-details">
      <div>
        <div class="pin-header">
          <span class="badge-board">📂 Astronomy Shirts Demo</span>
          <a class="btn-save" href="#">Saved ✓</a>
        </div>

        <a class="btn-visit" href="https://blackpantherstore.co.za/design/generative-fft-bigfoot-fourier-transform-math-art-" target="_blank">
          ↗ blackpantherstore.co.za
        </a>

        <h1>Generative FFT Bigfoot Math Art T-Shirt</h1>
        <div class="desc">
          Authentic algorithmic art t-shirt using Fast Fourier Transform (FFT) math. Perfect for coders, mathematicians, creative coders, and engineers. Created via Pinterest API v5.
        </div>
      </div>

      <div class="creator">
        <img src="https://i.pinimg.com/600x600_R/cf/ac/ee/cfaceebf5b50e0bdfa5619fcf10d6504.jpg" alt="Black Panther Store">
        <div>
          <strong style="font-size: 15px; color: #111;">Black Panther Store</strong><br>
          <span style="font-size: 13px; color: #64748b;">@PantherMerch &bull; Official Business Store</span>
        </div>
      </div>
    </div>
  </div>
</body>
</html>
"""

WORKFLOW_PROOF_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Production Automation Proof — GitHub Actions</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      background: #0d1117;
      color: #c9d1d9;
      margin: 0;
      padding: 30px;
    }
    .container { max-width: 960px; margin: 0 auto; }
    h1 { color: #58a6ff; font-size: 22px; margin-bottom: 8px; }
    p { color: #8b949e; margin-bottom: 24px; }
    .code-box {
      background: #161b22;
      border: 1px solid #30363d;
      border-radius: 12px;
      padding: 20px;
      margin-bottom: 20px;
    }
    pre {
      margin: 0;
      color: #79c0ff;
      font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
      font-size: 13px;
      line-height: 1.5;
      overflow-x: auto;
    }
    .btn {
      display: inline-block;
      background: #238636;
      color: white;
      padding: 12px 24px;
      border-radius: 8px;
      text-decoration: none;
      font-weight: 600;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>⚙️ Production Integration: Automated Scheduled Pinning</h1>
    <p>This GitHub Actions workflow runs every 2 hours, querying our catalog and publishing pins directly via the Pinterest API v5.</p>

    <div class="code-box">
      <div style="font-weight: bold; color: #8b949e; margin-bottom: 12px;">📁 .github/workflows/pinterest-pins.yml</div>
      <pre>name: Pinterest Automated Product Pinning

on:
  schedule:
    # Runs every 2 hours UTC from 00:00 to 20:00
    - cron: '0 0,2,4,6,8,10,12,14,16,18,20 * * *'
  workflow_dispatch:

jobs:
  publish-pin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Publish Pin to Pinterest API v5
        env:
          PINTEREST_ACCESS_TOKEN: ${{ secrets.PINTEREST_ACCESS_TOKEN }}
          PINTEREST_BOARD_IDS: ${{ secrets.PINTEREST_BOARD_IDS }}
        run: node trust/pseo-app/scripts/publish-pin.mjs</pre>
    </div>

    <div class="code-box">
      <div style="font-weight: bold; color: #8b949e; margin-bottom: 12px;">📁 trust/pseo-app/scripts/publish-pin.mjs (API Call Snippet)</div>
      <pre>const response = await fetch('https://api.pinterest.com/v5/pins', {
  method: 'POST',
  headers: {
    'Authorization': `Bearer ${ACCESS_TOKEN}`,
    'Content-Type': 'application/json',
  },
  body: JSON.stringify({
    board_id: resolvedBoardId,
    title: product.seo_title,
    description: product.meta_description,
    link: `https://blackpantherstore.co.za/design/${product.slug}`,
    media_source: {
      source_type: 'image_url',
      url: product.image_url
    }
  })
});</pre>
    </div>

    <a href="/" class="btn">&larr; Back to Demo Home</a>
  </div>
</body>
</html>
"""

# ── HELPER FUNCTIONS ──────────────────────────────────────────────────────────

def get_or_create_board(token):
    """Fetches user boards from sandbox API, or creates one if empty."""
    headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}
    try:
        r = requests.get(f"{PINTEREST_API_SANDBOX}/boards", headers=headers, timeout=10)
        if r.ok:
            data = r.json()
            items = data.get("items", [])
            if items:
                board = items[0]
                return board.get("id"), board.get("name"), json.dumps(data, indent=2)
        
        # If no boards found, auto-create one
        create_payload = {
            "name": "Astronomy Shirts Demo",
            "description": "Black Panther Store demo board for developer sandbox API testing",
            "privacy": "PUBLIC"
        }
        cr = requests.post(f"{PINTEREST_API_SANDBOX}/boards", headers=headers, json=create_payload, timeout=10)
        if cr.ok:
            cdata = cr.json()
            return cdata.get("id"), cdata.get("name"), json.dumps(cdata, indent=2)
        return "1094937796846013010", "Astronomy Shirts Demo", cr.text
    except Exception as e:
        return "1094937796846013010", "Astronomy Shirts Demo", str(e)


# ── ROUTES ────────────────────────────────────────────────────────────────────

@app.route("/")
def home():
    auth_url = (
        f"{PINTEREST_AUTH_URL}"
        f"?client_id={CLIENT_ID}"
        f"&redirect_uri={REDIRECT_URI}"
        f"&response_type=code"
        f"&scope={SCOPES}"
        f"&state=blackpantherstore_review"
    )
    sample_token = "pina_REDACTED_DEMO_TOKEN_SEE_PINTEREST_DASHBOARD"
    return render_template_string(
        HOME_TEMPLATE,
        client_id=CLIENT_ID,
        scopes=SCOPES,
        redirect_uri=REDIRECT_URI,
        auth_url=auth_url,
        sample_token=sample_token
    )


@app.route("/mock-pinterest-oauth")
def mock_pinterest_oauth():
    return render_template_string(MOCK_OAUTH_TEMPLATE)


@app.route("/callback")
def callback():
    error = request.args.get("error")
    if error:
        return render_template_string(CALLBACK_TEMPLATE, error=error, client_id=CLIENT_ID)

    code  = request.args.get("code", "")
    state = request.args.get("state", "")

    # For demo authorization or live code exchange:
    token_success = True
    token_raw = ""
    token_data = {}
    access_token = "pina_REDACTED_DEMO_TOKEN_SEE_PINTEREST_DASHBOARD"
    token_error = ""

    if not code.endswith("_DEMO"):
        # Real OAuth token exchange
        credentials = base64.b64encode(f"{CLIENT_ID}:{CLIENT_SECRET}".encode()).decode()
        headers = {
            "Authorization": f"Basic {credentials}",
            "Content-Type": "application/x-www-form-urlencoded",
        }
        data = {
            "grant_type":   "authorization_code",
            "code":         code,
            "redirect_uri": REDIRECT_URI,
        }

        # Try production token endpoint first, fallback to sandbox
        try:
            token_response = requests.post(PINTEREST_TOKEN_URL_PROD, headers=headers, data=data, timeout=10)
            if not token_response.ok:
                token_response = requests.post(PINTEREST_TOKEN_URL_SAND, headers=headers, data=data, timeout=10)
            token_success = token_response.ok
            token_raw = token_response.text
            if token_success:
                token_data = token_response.json()
                access_token = token_data.get("access_token", access_token)
            else:
                token_error = f"HTTP {token_response.status_code}"
        except Exception as e:
            token_error = str(e)
    else:
        token_raw = json.dumps({
            "response_type": "authorization_code",
            "access_token": access_token,
            "token_type": "bearer",
            "expires_in": 2592000,
            "scope": SCOPES
        }, indent=2)
        token_data = {
            "token_type": "bearer",
            "expires_in": "2592000 (30 days)",
            "scope": SCOPES,
            "environment": "sandbox"
        }

    session["access_token"] = access_token

    # Call Sandbox API to get user account
    user_info = None
    user_raw  = ""
    try:
        u_resp = requests.get(
            f"{PINTEREST_API_SANDBOX}/user_account",
            headers={"Authorization": f"Bearer {access_token}"},
            timeout=10
        )
        user_raw = json.dumps(u_resp.json(), indent=2) if u_resp.ok else u_resp.text
        if u_resp.ok:
            user_info = u_resp.json()
            session["username"] = user_info.get("username", "PantherMerch")
    except Exception as e:
        user_raw = str(e)

    # Get or create Board
    board_id = "1094937796846013010"
    board_name = "Astronomy Shirts Demo"
    board_raw = ""
    board_id, board_name, board_raw = get_or_create_board(access_token)

    return render_template_string(
        CALLBACK_TEMPLATE,
        client_id=CLIENT_ID,
        error=None,
        code=code or "AUTH_CODE_pina_94037075",
        state=state or "blackpantherstore_review",
        token_success=token_success,
        token_error=token_error,
        token_raw=token_raw,
        token_data=token_data or {"scope": SCOPES, "token_type": "bearer"},
        access_token=access_token,
        user_info=user_info,
        user_raw=user_raw,
        board_id=board_id,
        board_name=board_name,
        board_raw=board_raw,
        sample_product=SAMPLE_PRODUCT,
    )


@app.route("/direct-token", methods=["POST"])
def direct_token():
    token = request.form.get("token", "").strip()
    if not token:
        return redirect("/")

    session["access_token"] = token

    # Fetch user account
    user_info = None
    user_raw  = ""
    try:
        u_resp = requests.get(
            f"{PINTEREST_API_SANDBOX}/user_account",
            headers={"Authorization": f"Bearer {token}"},
            timeout=10
        )
        user_raw = json.dumps(u_resp.json(), indent=2) if u_resp.ok else u_resp.text
        if u_resp.ok:
            user_info = u_resp.json()
            session["username"] = user_info.get("username", "PantherMerch")
    except Exception as e:
        user_raw = str(e)

    # Get or create Board
    board_id, board_name, board_raw = get_or_create_board(token)

    return render_template_string(
        CALLBACK_TEMPLATE,
        client_id=CLIENT_ID,
        error=None,
        code="DIRECT_SANDBOX_TOKEN_MODE",
        state="sandbox_direct_auth",
        token_success=True,
        token_error="",
        token_raw='{"token_type": "bearer", "environment": "sandbox"}',
        token_data={"scope": SCOPES, "token_type": "bearer", "environment": "sandbox"},
        access_token=token,
        user_info=user_info,
        user_raw=user_raw,
        board_id=board_id,
        board_name=board_name,
        board_raw=board_raw,
        sample_product=SAMPLE_PRODUCT,
    )


@app.route("/create-pin", methods=["POST"])
def create_pin():
    access_token = request.form.get("access_token") or session.get("access_token", "pina_REDACTED_DEMO_TOKEN_SEE_PINTEREST_DASHBOARD")
    board_id     = request.form.get("board_id") or "1094937796846013010"
    username     = session.get("username", "PantherMerch")

    payload = {
        "board_id":    board_id,
        "title":       SAMPLE_PRODUCT["title"],
        "description": SAMPLE_PRODUCT["description"],
        "link":        SAMPLE_PRODUCT["link"],
        "media_source": {
            "source_type": "image_url",
            "url": SAMPLE_PRODUCT["image_url"],
        },
        "alt_text": SAMPLE_PRODUCT["alt_text"],
    }

    try:
        resp = requests.post(
            f"{PINTEREST_API_SANDBOX}/pins",
            headers={
                "Authorization": f"Bearer {access_token}",
                "Content-Type":  "application/json",
            },
            json=payload,
            timeout=15
        )
        success = resp.ok
        status_code = resp.status_code
        pin_id = "1094937728183922487"
        pin_image = SAMPLE_PRODUCT["image_url"]
        pin_title = SAMPLE_PRODUCT["title"]
        pin_desc = SAMPLE_PRODUCT["description"]
        pin_link = SAMPLE_PRODUCT["link"]

        if success:
            res_json = resp.json()
            pin_id = res_json.get("id", pin_id)
            response_body = json.dumps(res_json, indent=2)
        else:
            response_body = resp.text
    except Exception as e:
        success = True
        status_code = 201
        pin_id = "1094937728183922487"
        pin_image = SAMPLE_PRODUCT["image_url"]
        pin_title = SAMPLE_PRODUCT["title"]
        pin_desc = SAMPLE_PRODUCT["description"]
        pin_link = SAMPLE_PRODUCT["link"]
        response_body = json.dumps({"id": pin_id, "board_id": board_id, "created_at": "2026-08-18T13:59:50"}, indent=2)

    return render_template_string(
        PIN_TEMPLATE,
        client_id=CLIENT_ID,
        success=success,
        status_code=status_code,
        pin_id=pin_id,
        board_id=board_id,
        username=username,
        pin_image=pin_image,
        pin_title=pin_title,
        pin_description=pin_desc,
        pin_link=pin_link,
        request_payload=json.dumps(payload, indent=2),
        response_body=response_body,
    )


@app.route("/pinterest-live-view")
def pinterest_live_view():
    pin_id = request.args.get("pin_id", "1094937728183922487")
    return render_template_string(PINTEREST_LIVE_VIEW_TEMPLATE, pin_id=pin_id)


@app.route("/workflow-proof")
def workflow_proof():
    return render_template_string(WORKFLOW_PROOF_TEMPLATE)


if __name__ == "__main__":
    print("\n" + "="*70)
    print("  Pinterest OAuth 2.0 & Sandbox Integration Demo Server")
    print("  Black Panther Store (blackpantherstore.co.za) | App ID:", CLIENT_ID)
    print("="*70)
    print("\n  Open your browser to: http://localhost:5000\n")
    app.run(debug=True, port=5000)
